//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace fBlockBuster.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class BlockBusterDBEntities : DbContext
    {
        public BlockBusterDBEntities()
            : base("name=BlockBusterDBEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<tblArticulo> tblArticulo { get; set; }
        public virtual DbSet<tblArticuloDetalle> tblArticuloDetalle { get; set; }
        public virtual DbSet<tblArticuloTransaccion> tblArticuloTransaccion { get; set; }
        public virtual DbSet<tblEstado> tblEstado { get; set; }
        public virtual DbSet<tblGenero> tblGenero { get; set; }
        public virtual DbSet<tblRating> tblRating { get; set; }
        public virtual DbSet<tblTipo> tblTipo { get; set; }
        public virtual DbSet<tblTransaccion> tblTransaccion { get; set; }
        public virtual DbSet<tblUsuario> tblUsuario { get; set; }
    }
}
