//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace fBlockBuster.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblTransaccion
    {
        public int idTransaccion { get; set; }
        public int idTipo { get; set; }
        public Nullable<int> idEstado { get; set; }
        public int idUsuario { get; set; }
        public int idArticulo { get; set; }
        public decimal Precio { get; set; }
        public Nullable<System.TimeSpan> Duracion { get; set; }
        public Nullable<System.DateTime> Fecha { get; set; }
    
        public virtual tblArticulo tblArticulo { get; set; }
        public virtual tblEstado tblEstado { get; set; }
        public virtual tblTipo tblTipo { get; set; }
        public virtual tblUsuario tblUsuario { get; set; }
    }
}
