//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace fBlockBuster.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblTransaccion
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public tblTransaccion()
        {
            this.tblArticuloTransaccion = new HashSet<tblArticuloTransaccion>();
        }
    
        public int idTransaccion { get; set; }
        public int idTipo { get; set; }
        public Nullable<int> idEstado { get; set; }
        public int idUsuario { get; set; }
        public decimal Precio { get; set; }
        public Nullable<System.DateTime> Fecha { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tblArticuloTransaccion> tblArticuloTransaccion { get; set; }
        public virtual tblEstado tblEstado { get; set; }
        public virtual tblTipo tblTipo { get; set; }
        public virtual tblUsuario tblUsuario { get; set; }
    }
}
