//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace fBlockBuster.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblUsuario
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public tblUsuario()
        {
            this.tblTransaccion = new HashSet<tblTransaccion>();
        }
    
        public int idUsuario { get; set; }
        public int idTipo { get; set; }
        public string NombreUsuario { get; set; }
        public string Correo { get; set; }
        public string PasswordUsuario { get; set; }
        public Nullable<System.DateTime> CreadoEn { get; set; }
    
        public virtual tblTipo tblTipo { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tblTransaccion> tblTransaccion { get; set; }
    }
}
